DELIMITER //

DROP FUNCTION IF EXISTS Nonce //
CREATE FUNCTION Nonce(LENGTH INTEGER) RETURNS TEXT
BEGIN
	RETURN SUBSTRING(UPPER(SHA2(MD5(CAST(FLOOR(RAND()*(999999999999)) AS CHAR)), 256)), 1, LENGTH);
END //

DROP FUNCTION IF EXISTS UnixToDate //
CREATE FUNCTION UnixToDate(unix_time INTEGER) RETURNS DATETIME
BEGIN
	RETURN CONVERT_TZ(FROM_UNIXTIME(unix_time), 'SYSTEM', '+00:00');
END //

DROP FUNCTION IF EXISTS SHA256 //
CREATE FUNCTION SHA256 (DATA TEXT) RETURNS TEXT
BEGIN
    RETURN UPPER(SHA2(DATA, 256));
END //